spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}?stringtype=unspecified
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  sql:
    init:
      mode: always
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      schema-locations: classpath:db/schema-postgres.sql,classpath:db/schema-postgres-demo.sql
      data-locations: classpath:db/data-postgres.sql,classpath:db/data-postgres-demo.sql

s2:
  embedding:
    store:
      provider: PGVECTOR
      base:
        url: ${DB_HOST}
      port: ${DB_PORT:5432}
      databaseName: ${DB_NAME}
      user: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      dimension: 512