s2:
  schema:
    cache:
      enable: true

  parser:
    chat:
      history:
        num: 10
        seconds: 600
    strategy: ONE_PASS_SELF_CONSISTENCY
    exemplar-recall:
      number: 10
    few-shot:
      number: 5
    self-consistency:
      number: 1
    multi-turn:
      enable: false

  corrector:
    additional:
      information: true
    date: true

  demo:
    names: S2VisitsDemo,S2SingerDemo,S2CompanyDemo,S2SmallTalkDemo
    enableLLM: true

  authentication:
    enable: true
    exclude:
      path: /api/auth/user/register,/api/auth/user/login,/api/chat/agent/hasAgentRight
    token:
      http:
        header:
          key: Authorization

  mapper:
    name:
      threshold: 0.30
      min:
        threshold:value: 0.25
    value:
      threshold: 0.5
      min:
        threshold: 0.3
    embedding:
      use-llm-enhance: false
      use-llm-words-segement: true

  manage:
    chat:
      agent:
        ids: 1,3,5  # chatAgentIds
      model:
        ids: 9,19,29,33  # chatModelIds
      dataBase:
        ids: 1,2,3    # chatDatabaseIds
      domain:
        ids: 1,2,3    # chatDomainIds
    parser:
      agent:
        ids: 43

  dimension:
    mapping:
      pid1_2022: "717"
      pid2_2022: "719"
      pid3_2022: "721"
      pid4_2022: "723"
      dataSet: 31
    database:
      name: "bvreport"

crab:
  api:
    appId: kuaesoba
    secretKey: e66a04b5e44748ebbeb119adc047f02d
    host: https://crab.migu.cn
    file:
      serviceName: deepseek_whole
      serviceType: file_parse
      urls:
        upload: /crab/api/resource/aimanager/task/upload
        parse: /crab/api/aigc/task/bigmodel/deep/file/aysn/parse
        status: /crab/api/aigc/task/bigmodel/deep/file/aysn/status
    deepseek:
      url: /crab/api/aigc/task/bigmodel/deepseek
      serviceName: deepseek_32B
      serviceType: text_to_text